### ISSUE TITLE
issue on dual monitor v1.3.2

### ISSUE THREAD

**Issue by cll00** [sandydoo/flux-screensavers#14]
hi @sandydoo 

i found a error on dual monitor configuration

monitor 1 = 4k
monitor 2 = 1080p
![WhatsApp Image 2023-03-14 at 18 05 40](https://user-images.githubusercontent.com/564881/225137285-d0388c3e-415c-4162-8dca-eb5e4c3dbd47.jpeg)

**Comment by sandydoo** [comment]
Thanks for the picture! That's very helpful. I'll investigate.

**Comment by sandydoo** [comment]
I finally found a second monitor to test this out. I can replicate it, but I'm still not sure why it's happening.

**Comment by sandydoo** [comment]
I've found a number of breaking issues with [winit](https://github.com/rust-windowing/winit):
* Incorrect window sizing when using monitors with different scalings
* Incorrect window positions when using undecorated (borderless windows)

I'll be switching back to SDL2 in v1.4.
