### ISSUE TITLE
Screensaver causes Windows to disable HDR without restoring the setting

### ISSUE THREAD

**Issue by sandydoo** [sandydoo/flux-screensavers#17]
Flux doesn't use HDR and the problem is that Windows isn't restoring the setting back to what it was. This really isn't our fault, but it is annoying for people with HDR monitors, so we need to figure out a workaround.

I'm not sure how to tackle this, partly because I don't own an HDR monitor...

I see two options:
1. Use some API (nvapi for nvidia cards?) to query and then restore the value of the HDR setting when quitting.
2. Request an HDR compatible surface. I don't know if this needs to be 10bit or f32. I also have no idea if this will result in washed out colors.

**Comment by sandydoo** [comment]
Maybe #15 will help with this. Maybe Windows doesn't like that we're an SDR app in windowed mode.

**Comment by sandydoo** [comment]
This is a common issue with OpenGL and Vulkan apps. It appears that the graphics driver is detecting that Flux is running in windowed-borderless mode at the resolution of the monitor and is switching to exclusive-fullscreen. This changes the video-mode to SDR and Windows fails to switch back to HDR once the screensaver exits.

OpenGL does not have an API to disable this behaviour. Manually disabling fullscreen optimisation in Windows also does not appear to help.

Nvidia has a new setting that can automatically render OpenGL apps to a DXGI swapchain, which in theory could avoid this issue. This is currently opt-in and is Nvidia-only.

1. We could try requesting an HDR-compatible surface. Probably float16? The problem is that we don't know the maximum range of the monitor and we'd have to tell modify flux to output color values beyond 0-1.
2. We could try managing our own DXGI swapchain. This might be what AAA games do, but I'm unsure how much work this would be.
3. We rewrite Flux to use WGPU and DirectX. This is a lot of work.

**Comment by sandydoo** [comment]
Going with option 3, before eventually moving to wgpu. https://github.com/sandydoo/flux-screensavers/tree/feature/dxgi-swapchain

**Comment by sunseraphic** [comment]
FYI.

Yesterday, I just purchased the Windows screensaver and download the v1.4.0 to my gaming PC connected to a HDR TV. And then I was always annoyed with the HDR turn-off issue. Every time when I tried to recover from the screensaver to desktop, It seems that Windows always tried to re-enable HDR mode, the HDMI Invalid Format error would come out. I had to reconnect the HDMI cable to resolve this issue time and time again. 

I just tried to use the Nvidia setting mentioned above to mitigate this issue, it seems work. And I also downloaded the v1.5.0 Beta 0, it seems also work.

**Comment by sandydoo** [comment]
> I just tried to use the Nvidia setting mentioned above to mitigate this issue, it seems work. And I also downloaded the v1.5.0 Beta 0, it seems also work.

Thanks for the feedback! v1.5 tries to use the same technique that Nvidia does when that setting is enabled. This was such a pain to fix, so I'm really happy to hear that it's working!
