### ISSUE TITLE
Seemless multimonitor on macOS?

### ISSUE THREAD

**Issue by asoji** [sandydoo/flux-screensavers#25]
Would it possible to have the screensaver span across all monitors seemlessly on macOS? I know on Windows, it spans across all monitors seemlessly just fine, but it looks[?] like on macOS, every monitor is its own separate instance?

**Comment by sandydoo** [comment]
In theory, yes, it's possible. But it's a ton of work to figure out, especially with OpenGL and legacyScreenSaver, so I won't be tackling this one.
