### ISSUE TITLE
Can’t open .exe file after building.

### ISSUE THREAD

**Issue by neyako** [sandydoo/flux-screensavers#3]
I tried to build from the source from Windows (used MSVC instead GNU) and in target folder, it has a .exe

But when I open it, it keeps open flux settings and says “coming soon”. Also I don’t see any .scr file for screensaver.

Any idea?

**Comment by sandydoo** [comment]
You can rename it to .src, right-click, and install.

**Comment by neyako** [comment]
It’s worked! Thanks!
